#!/bin/bash
# clingo+lua: cannot example
# Author: Thomas Krennwallner <tkren@kr.tuwien.ac.at>
# Date: 2018-02-04

set -o pipefail

clingo /usr/share/doc/gringo/examples/clingo/cannot/{cannot-lua,example}.lp

result=$?
test $result -eq 30
